### ISSUE TITLE
最新的镜像无法工作

### ISSUE THREAD

**Issue by sakarie9** [Clansty/Q2TG#116]
```
[2023-05-11T12:54:39.129] [DEBUG] Instance - 0 - 正在登录 TG Bot
[2023-05-11T12:54:39.132] [INFO] - [Running gramJS version 2.15.8]
[2023-05-11T12:54:39.703] [INFO] Instance - 0 - TG Bot 登录完成
[2023-05-11T12:54:39.704] [DEBUG] Instance - 0 - 正在登录 TG UserBot
[2023-05-11T12:54:39.705] [INFO] - [Running gramJS version 2.15.8]
[2023-05-11T12:54:40.251] [INFO] Instance - 0 - TG UserBot 登录完成
[2023-05-11T12:54:40.502] [DEBUG] Instance - 0 - 正在登录 OICQ
[2023-05-11T12:54:40.513] [MARK] [iPad:*] - ----------
[2023-05-11T12:54:40.513] [MARK] [iPad:*] - Package Version: oicq@2.3.14-clansty (Released on 2023/5/10)
[2023-05-11T12:54:40.514] [MARK] [iPad:*] - View Changelogs：https://github.com/takayama-lily/oicq/releases
[2023-05-11T12:54:40.514] [MARK] [iPad:*] - ----------
[2023-05-11T12:54:40.526] [ERROR] Main - UnhandledException:  Error: error:0308010C:digital envelope routines::unsupported
    at Cipheriv.createCipherBase (node:internal/crypto/cipher:116:19)
    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:135:3)
    at new Cipheriv (node:internal/crypto/cipher:243:3)
    at Object.createCipheriv (node:crypto:141:10)
    at sign (/nix/store/j7rii50cfb9ba9mrixy511335x56niad-q2tg/libexec/q2tg/node_modules/oicq/lib/core/t544.js:484:25)
    at 1348 (/nix/store/j7rii50cfb9ba9mrixy511335x56niad-q2tg/libexec/q2tg/node_modules/oicq/lib/core/tlv.js:361:22)
    at OicqClient.packTlv (/nix/store/j7rii50cfb9ba9mrixy511335x56niad-q2tg/libexec/q2tg/node_modules/oicq/lib/core/tlv.js:38:24)
    at OicqClient.passwordLogin (/nix/store/j7rii50cfb9ba9mrixy511335x56niad-q2tg/libexec/q2tg/node_modules/oicq/lib/core/base-client.js:312:31)
    at OicqClient.login (/nix/store/j7rii50cfb9ba9mrixy511335x56niad-q2tg/libexec/q2tg/node_modules/oicq/lib/client.js:206:35) {
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

**Comment by clansty** [comment]
NODE_OPTIONS=--openssl-legacy-provider

**Comment by sakarie9** [comment]
懂了，加进docker-compose.yaml的environment后面
