### ISSUE TITLE
UnhandledException:  TypeError: Cannot read properties of undefined (reading 'initMapInstance')

### ISSUE THREAD

**Issue by ayaka14732** [Clansty/Q2TG#117]
使用最新的 commit https://github.com/Clansty/Q2TG/commit/279b05e1a34c28cb09e794cac08a077fa99696b4 出現報錯：

```
Prisma schema loaded from nix/store/j7rii50cfb9ba9mrixy511335x56niad-q2tg/libexec/q2tg/node_modules/.prisma/client/schema.prisma
Datasource "db": PostgreSQL database "q2tg-data", schema "public" at "127.0.0.1:5432"

⚠  There might be data loss when applying the changes:

  • You are about to drop the column `qqPassword` on the `Instance` table, which still contains 1 non-null values.
  • You are about to drop the column `qqPlatform` on the `Instance` table, which still contains 1 non-null values.
  • You are about to drop the column `qqUin` on the `Instance` table, which still contains 1 non-null values.
  • You are about to drop the column `name` on the `Session` table, which still contains 2 non-null values.


🚀  Your database is now in sync with your Prisma schema. Done in 4.23s

[LOG] Emoji versions: 0.6, 0.7, 1.0, 2.0, 3.0, 4.0, 5.0, 11.0, 12.0, 12.1, 13.0, 13.1, 14.0, esq.latest, nfq.latest, xdd.latest
[LOG] EmojiDB loaded 4828 entries.
[LOG] Emoji versions: 0.6, 0.7, 1.0, 2.0, 3.0, 4.0, 5.0, 11.0, 12.0, 12.1, 13.0, 13.1, 14.0, esq.latest, nfq.latest, xdd.latest
[LOG] EmojiDB loaded 4828 entries.
[2023-05-11T14:22:19.455] [DEBUG] Instance - 0 - 正在登录 TG Bot
[2023-05-11T14:22:19.458] [INFO] - [Running gramJS version 2.15.8]
[2023-05-11T14:22:19.458] [DEBUG] TelegramSession - undefined - Session 不存在，创建[2023-05-11T14:22:27.208] [INFO] Instance - 0 - TG Bot 登录完成[2023-05-11T14:22:27.208] [DEBUG] Instance - 0 - 正在登录 TG UserBot
[2023-05-11T14:22:27.209] [INFO] - [Running gramJS version 2.15.8]
[2023-05-11T14:22:27.209] [DEBUG] TelegramSession - null - Session 不存在，创建[2023-05-11T14:22:29.918] [ERROR] Main - UnhandledException:  RPCError: 401: AUTH_KEY_UNREGISTERED (caused by users.GetUsers)
    at RPCMessageToError (/nix/store/j7rii50cfb9ba9mrixy511335x56niad-q2tg/libexec/q2tg/node_modules/telegram/errors/index.js:28:12)
    at MTProtoSender._handleRPCResult (/nix/store/j7rii50cfb9ba9mrixy511335x56niad-q2tg/libexec/q2tg/node_modules/telegram/network/MTProtoSender.js:517:58)
    at MTProtoSender._processMessage (/nix/store/j7rii50cfb9ba9mrixy511335x56niad-q2tg/libexec/q2tg/node_modules/telegram/network/MTProtoSender.js:442:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MTProtoSender._recvLoop (/nix/store/j7rii50cfb9ba9mrixy511335x56niad-q2tg/libexec/q2tg/node_modules/telegram/network/MTProtoSender.js:418:17) {
  code: 401,
  errorMessage: 'AUTH_KEY_UNREGISTERED'
}
[2023-05-11T14:22:42.213] [INFO] Main - 开始加载 MapInstance
[2023-05-11T14:22:42.214] [ERROR] Main - UnhandledException:  TypeError: Cannot read properties of undefined (reading 'initMapInstance')
    at Timeout._onTimeout (/nix/store/j7rii50cfb9ba9mrixy511335x56niad-q2tg/libexec/q2tg/build/index.js:35:41)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
```

**Comment by sbbbsbbb** [comment]
遇到同样的问题，请问你怎么解决的

**Comment by ayaka14732** [comment]
是沒有解決，已經無法使用了

**Comment by clansty** [comment]
map instance 那个不用管，如果是无法登陆的话需要搭建签名 API

**Comment by clansty** [comment]
看了一下最上面的输出，应该是更新大版本了，需要删除数据库重新配置
