### ISSUE TITLE
[Bug Report] 使用最新版本镜像所有协议均无法登录QQ，回退到 279b05e 可以正常登录

### ISSUE THREAD

**Issue by ERR0RPR0MPT** [Clansty/Q2TG#126]
## 描述
早上使用了安卓平板、iPad登录都无法成功，使用macOS登录成功了
但在登录成功一个小时之后就出现了client not online的情况，再次登录使用macOS仍然提示禁止登录。

貌似先前作者更换了icqq来替代oicq（实在不行可以参考一下隔壁的go-cqhttp的实现）。感谢作者和contributer们的付出

**Comment by ERR0RPR0MPT** [comment]
重建了q2tg并且发了几条消息貌似解除了风控，看来不是项目的问题，误会了

**Comment by sakarie9** [comment]
一样的问题，所有协议都登陆失败

279b05e1a34c28cb09e794cac08a077fa99696b4 才能登陆

**Comment by sakarie9** [comment]
最新的 commit 只有清空数据后选 mac 协议才可以登陆

其他的协议都会显示
```
[2023-07-06T12:27:22.246] [INFO] [icqq] - [***]使用协议：iPad_8.9.63.11390
[2023-07-06T12:27:22.567] [WARN] [icqq] - token失效: [禁止登录]登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。(错误码：45)
[2023-07-06T12:27:22.567] [ERROR] [icqq] - [禁止登录]登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。
[2023-07-06T12:27:22.567] [ERROR] Main - UnhandledException:  [禁止登录]登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。
```

大概确实是 bug, issue 重开一下吧（

**Comment by ERR0RPR0MPT** [comment]
> 最新的 commit 只有清空数据后选 mac 协议才可以登陆
> 
> 其他的协议都会显示
> 
> ```
> [2023-07-06T12:27:22.246] [INFO] [icqq] - [***]使用协议：iPad_8.9.63.11390
> [2023-07-06T12:27:22.567] [WARN] [icqq] - token失效: [禁止登录]登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。(错误码：45)
> [2023-07-06T12:27:22.567] [ERROR] [icqq] - [禁止登录]登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。
> [2023-07-06T12:27:22.567] [ERROR] Main - UnhandledException:  [禁止登录]登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。
> ```
> 
> 大概确实是 bug, issue 重开一下吧（

草，昨天又掉了，我试试你这个版本

**Comment by ERR0RPR0MPT** [comment]
@sakarie9 情况属实，确实是最新版有问题

使用版本 https://github.com/Clansty/Q2TG/commit/279b05e1a34c28cb09e794cac08a077fa99696b4 能避免最新版无法登录的问题（这个版本还没换后端，还是oicq）

我这边使用 macOS 登录正常，但使用 iPad 方式登录报错：

```shell
[2023-07-08T05:34:52.362] [ERROR] Main - UnhandledException:  Error: error:0308010C:digital envelope routines::unsupported
    at Cipheriv.createCipherBase (node:internal/crypto/cipher:116:19)
    at Cipheriv.createCipherWithIV (node:internal/crypto/cipher:135:3)
    at new Cipheriv (node:internal/crypto/cipher:243:3)
    at Object.createCipheriv (node:crypto:141:10)
    at sign (/nix/store/j7rii50cfb9ba9mrixy511335x56niad-q2tg/libexec/q2tg/node_modules/oicq/lib/core/t544.js:484:25)
    at 1348 (/nix/store/j7rii50cfb9ba9mrixy511335x56niad-q2tg/libexec/q2tg/node_modules/oicq/lib/core/tlv.js:361:22)
    at OicqClient.packTlv (/nix/store/j7rii50cfb9ba9mrixy511335x56niad-q2tg/libexec/q2tg/node_modules/oicq/lib/core/tlv.js:38:24)
    at OicqClient.passwordLogin (/nix/store/j7rii50cfb9ba9mrixy511335x56niad-q2tg/libexec/q2tg/node_modules/oicq/lib/core/base-client.js:312:31)
    at OicqClient.login (/nix/store/j7rii50cfb9ba9mrixy511335x56niad-q2tg/libexec/q2tg/node_modules/oicq/lib/client.js:206:35) {
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

登录的时候甚至不需要验证码（

**Comment by clansty** [comment]
看前面的 issue，要加一个环境变量

**Comment by ERR0RPR0MPT** [comment]
> 看前面的 issue，要加一个环境变量

#116 应该是解决上面问题的issue

目前的最大问题还是在线一段时间之后出现：

![image](https://github.com/Clansty/Q2TG/assets/118054130/cabe4f98-60da-48f3-b8c5-4b5d2f9ea9f1)

然后QQ端就离线了，几次都是这样

并且每次都是在线1-2小时就掉了，~~tx死妈~~

**Comment by ERR0RPR0MPT** [comment]
report: 使用 https://github.com/Clansty/Q2TG/commit/279b05e1a34c28cb09e794cac08a077fa99696b4 的 iPad 协议连续一周正常使用，此 issue 暂时关闭。
