### ISSUE TITLE
创建TG文件夹时失败

### ISSUE THREAD

**Issue by eaglu** [Clansty/Q2TG#14]
设置文件夹失败 RPCError: 400: DIALOG_FILTERS_TOO_MUCH (caused by messages.UpdateDialogFilter)
main_q2tg        |     at Object.RPCMessageToError (/app/node_modules/telegram/errors/index.js:24:12)
main_q2tg        |     at MTProtoSender._handleRPCResult (/app/node_modules/telegram/network/MTProtoSender.js:483:36)
main_q2tg        |     at MTProtoSender._processMessage (/app/node_modules/telegram/network/MTProtoSender.js:408:15)
main_q2tg        |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
main_q2tg        |     at async MTProtoSender._recvLoop (/app/node_modules/telegram/network/MTProtoSender.js:384:17) {
main_q2tg        |   code: 400,
main_q2tg        |   errorMessage: 'DIALOG_FILTERS_TOO_MUCH'
main_q2tg        | }

**Comment by eaglu** [comment]
是自己的原因。不好意思
