### ISSUE TITLE
无法使用 host.docker.internal 连接到 host ?

### ISSUE THREAD

**Issue by iceBear67** [Clansty/Q2TG#21]
不是 docker 高手，不知道怎么做了

```
[2022-07-01T13:43:30.701Z] [ERROR] - [WebSocket connection failed attempt: 5]
SocksClientError: getaddrinfo ENOTFOUND host.docker.internal
    at SocksClient.closeSocket (/app/node_modules/socks/build/client/socksclient.js:388:32)
    at SocksClient.onErrorHandler (/app/node_modules/socks/build/client/socksclient.js:361:14)
    at Socket.onError (/app/node_modules/socks/build/client/socksclient.js:223:38)
    at Object.onceWrapper (node:events:642:26)
    at Socket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:164:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  options: {
    proxy: {
      host: 'host.docker.internal',
      port: 1080,
      type: 5,
      userId: undefined,
      password: undefined
    },
    command: 'connect',
    timeout: 5000,
    destination: { host: '149.154.167.91', port: 80 }
  }
}

```
~~是我对这玩意有误解吗，求指教，或者有别的什么方法连到host?~~

**Comment by clansty** [comment]
直接指定 host 的 ip
