### ISSUE TITLE
tg转发qq失败，提示INVALID_URL

### ISSUE THREAD

**Issue by magisk317** [Clansty/Q2TG#235]
log如下：
```
[2024-04-26T03:14:52.815] [ERROR] ForwardService - 0 - 从 TG 到 QQ 的消息转发失败 TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:405:5)
    at new URL (node:internal/url:676:13)
    at Object.generateTelegramAvatarUrl (/app/build/helpers/forwardHelper.js:192:21)
    at ForwardService.forwardFromTelegram (/app/build/services/ForwardService.js:455:71)
    at onTelegramMessage (/app/build/controllers/ForwardController.js:114:62)
    at onMessage (/app/build/client/Telegram.js:87:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _dispatchUpdate (/app/node_modules/.pnpm/@github.com+clansty+gramjs+releases+download+2.19.10%25252525252525252525252525252525252Breve_vvonrr7fh6cxy2qgcstda2o72u/node_modules/telegram/client/updates.js:144:21) {
  input: 'undefined/telegramAvatar/0/1814997942',
  code: 'ERR_INVALID_URL'
}
```

**Comment by magisk317** [comment]
貌似是因为docker打包失败导致的。。。大佬帮忙重启下打包任务吧

https://github.com/clansty/Q2TG/actions/runs/8541362023/job/23400489021

**Comment by magisk317** [comment]
done
