### ISSUE TITLE
[BUG] 消息内同时包含超级表情和文字时转发失败

### ISSUE THREAD

**Issue by sakarie9** [Clansty/Q2TG#237]
复现：

![图片](https://github.com/clansty/Q2TG/assets/20642596/0bbdadef-fa3e-4913-9e2c-fdb5014cef6b)

![图片](https://github.com/clansty/Q2TG/assets/20642596/5510963e-f897-4938-a110-5b658830cc81)

LOG：

```
[2024-05-27T09:07:36.253] [ERROR] ForwardService - 0 - 从 QQ 到 TG 的消息转发失败 
TypeError: text.replace is not a function
    at Object.htmlEscape (/app/build/helpers/forwardHelper.js:14:35)
    at ForwardService.forwardFromQq (/app/build/services/ForwardService.js:167:67)
    at onQqMessage (/app/build/controllers/ForwardController.js:62:75)
    at OicqClient.onMessage (/app/build/client/OicqClient.js:108:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by clansty** [comment]
fixed
