### ISSUE TITLE
机器人在TG上被踢后无法重新加入原群

### ISSUE THREAD

**Issue by Leao9203** [Clansty/Q2TG#41]
复现：在将机器人在 TG 上踢出群后，重启一次机器人，然后使用 `/addgroup` 命令来重新转发该 QQ 群，创建转发时选择的方法为 `手动选择现有群组`，选择在 TG 上被踢出的群，成功将机器人添加到这个群之后，出现报错

<details>
<summary>在 TG 上的报错</summary>

```
Leao的Q2TG机器人, [2022/8/22 22:49]
创建群组并关联失败
Error: 
Invalid `db_1.default.forwardPair.create()` invocation in
/app/build/models/ForwardPairs.js:42:56

  39     return instance;
  40 }
  41 async add(qq, tg) {
→ 42     const dbEntry = await db_1.default.forwardPair.create(
  Unique constraint failed on the fields: (`qqRoomId`,`instanceId`)

Leao的Q2TG机器人, [2022/8/22 22:50]
创建群组并关联失败
Error: 
Invalid `db_1.default.forwardPair.create()` invocation in
/app/build/models/ForwardPairs.js:42:56

  39     return instance;
  40 }
  41 async add(qq, tg) {
→ 42     const dbEntry = await db_1.default.forwardPair.create(
  Unique constraint failed on the fields: (`qqRoomId`,`instanceId`)
```

</details>

<details>
<summary>在控制台上的报错</summary>

```
main_q2tg        | [2022-08-22T14:47:17.133] [INFO] Instance - 0 - OICQ 登录完成   
main_q2tg        | [2022-08-22T14:47:24.187] [WARN] ForwardPairs - 0 - 初始化遇到问题，QQ: -*****0696 TG: ******3648
main_q2tg        | [2022-08-22T14:47:34.800] [INFO] Instance - 0 - 初始化已完成
main_q2tg        | [2022-08-22T14:47:35.706] [INFO] Instance - 0 - 命令设置成功
main_q2tg        | [2022-08-22T14:49:23.042] [INFO] ConfigService - 0 - 创建群组并关 联：-*****0696
postgresql_q2tg  | 2022-08-22 14:49:26.852 UTC [37] ERROR:  duplicate key value violates unique constraint "ForwardPair_qqRoomId_instanceId_key"
postgresql_q2tg  | 2022-08-22 14:49:26.852 UTC [37] DETAIL:  Key ("qqRoomId", "instanceId")=(-*****0696, 0) already exists.
postgresql_q2tg  | 2022-08-22 14:49:26.852 UTC [37] STATEMENT:  INSERT INTO "public"."ForwardPair" ("qqRoomId","tgChatId","instanceId","joinNotice","poke","enable") VALUES ($1,$2,$3,$4,$5,$6) RETURNING "public"."ForwardPair"."id"
main_q2tg        | [2022-08-22T14:49:26.869] [ERROR] ConfigService - 0 - 创建群组并关联失败 PrismaClientKnownRequestError:
main_q2tg        | Invalid `db_1.default.forwardPair.create()` invocation in
main_q2tg        | /app/build/models/ForwardPairs.js:42:56
main_q2tg        | 
main_q2tg        |   39     return instance;
main_q2tg        |   40 }
main_q2tg        |   41 async add(qq, tg) {
main_q2tg        | → 42     const dbEntry = await db_1.default.forwardPair.create(
main_q2tg        |   Unique constraint failed on the fields: (`qqRoomId`,`instanceId`)
main_q2tg        |     at RequestHandler.handleRequestError (/app/node_modules/@prisma/client/runtime/index.js:28658:13)
main_q2tg        |     at RequestHandler.request (/app/node_modules/@prisma/client/runtime/index.js:28640:12)
main_q2tg        |     at async consumer (/app/node_modules/@prisma/client/runtime/index.js:29618:18)
main_q2tg        |     at async PrismaClient._request (/app/node_modules/@prisma/client/runtime/index.js:29639:16)
main_q2tg        |     at async ForwardPairs.add (/app/build/models/ForwardPairs.js:42:25)
main_q2tg        |     at async ConfigService.createGroupAndLink (/app/build/services/ConfigService.js:178:28)
main_q2tg        |     at async ConfigService.createLinkGroup (/app/build/services/ConfigService.js:245:13)
main_q2tg        |     at async handleMessage (/app/build/controllers/ConfigController.js:41:17)
main_q2tg        |     at async onMessage (/app/build/client/Telegram.js:66:25)
main_q2tg        |     at async _dispatchUpdate (/app/node_modules/telegram/client/updates.js:141:21) {
main_q2tg        |   code: 'P2002',
main_q2tg        |   clientVersion: '4.1.1',
main_q2tg        |   meta: { target: [ 'qqRoomId', 'instanceId' ] }
main_q2tg        | }
main_q2tg        | [2022-08-22T14:50:05.980] [INFO] ConfigService - 0 - 创建群组并关 联：-*****0696
postgresql_q2tg  | 2022-08-22 14:50:10.686 UTC [36] ERROR:  duplicate key value violates unique constraint "ForwardPair_qqRoomId_instanceId_key"
postgresql_q2tg  | 2022-08-22 14:50:10.686 UTC [36] DETAIL:  Key ("qqRoomId", "instanceId")=(-*****0696, 0) already exists.
postgresql_q2tg  | 2022-08-22 14:50:10.686 UTC [36] STATEMENT:  INSERT INTO "public"."ForwardPair" ("qqRoomId","tgChatId","instanceId","joinNotice","poke","enable") VALUES ($1,$2,$3,$4,$5,$6) RETURNING "public"."ForwardPair"."id"
main_q2tg        | [2022-08-22T14:50:10.693] [ERROR] ConfigService - 0 - 创建群组并关联失败 PrismaClientKnownRequestError:
main_q2tg        | Invalid `db_1.default.forwardPair.create()` invocation in
main_q2tg        | /app/build/models/ForwardPairs.js:42:56
main_q2tg        | 
main_q2tg        |   39     return instance;
main_q2tg        |   40 }
main_q2tg        |   41 async add(qq, tg) {
main_q2tg        | → 42     const dbEntry = await db_1.default.forwardPair.create(
main_q2tg        |   Unique constraint failed on the fields: (`qqRoomId`,`instanceId`)
main_q2tg        |     at RequestHandler.handleRequestError (/app/node_modules/@prisma/client/runtime/index.js:28658:13)
main_q2tg        |     at RequestHandler.request (/app/node_modules/@prisma/client/runtime/index.js:28640:12)
main_q2tg        |     at async consumer (/app/node_modules/@prisma/client/runtime/index.js:29618:18)
main_q2tg        |     at async PrismaClient._request (/app/node_modules/@prisma/client/runtime/index.js:29639:16)
main_q2tg        |     at async ForwardPairs.add (/app/build/models/ForwardPairs.js:42:25)
main_q2tg        |     at async ConfigService.createGroupAndLink (/app/build/services/ConfigService.js:178:28)
main_q2tg        |     at async ConfigService.createLinkGroup (/app/build/services/ConfigService.js:245:13)
main_q2tg        |     at async handleMessage (/app/build/controllers/ConfigController.js:41:17)
main_q2tg        |     at async onMessage (/app/build/client/Telegram.js:66:25)
main_q2tg        |     at async _dispatchUpdate (/app/node_modules/telegram/client/updates.js:141:21) {
main_q2tg        |   code: 'P2002',
main_q2tg        |   clientVersion: '4.1.1',
main_q2tg        |   meta: { target: [ 'qqRoomId', 'instanceId' ] }
main_q2tg        | }

```

</details>

**Comment by clansty** [comment]
手动进数据库删除，重启机器人，重新添加

**Comment by Leao9203** [comment]
> 手动进数据库删除，重启机器人，重新添加

删除数据库中的哪个文件...求解

**Comment by clansty** [comment]
pairs 里面的东西
