### ISSUE TITLE
添加机器人到群时的报错

### ISSUE THREAD

**Issue by Leao9203** [Clansty/Q2TG#42]
看起来是概率性出现的报错，因为在出现这个报错之后再添加机器人一次就会正常

![image](https://user-images.githubusercontent.com/45661339/186213363-9a1112b5-4a02-4efc-8619-48428f5c68c6.png)

顺带一提，出现这个报错的时候，机器人不会给出任何回复，只有控制台有输出

<details>
<summary>控制台的输出</summary>

```
main_q2tg        | Error: Could not find the input entity for {"userId":"******1138","className":"PeerUser"}.
main_q2tg        |          Please read https://docs.telethon.dev/en/latest/concepts/entities.html to find out more details.
main_q2tg        |     at Object.getInputEntity (/app/node_modules/telegram/client/users.js:297:11)
main_q2tg        |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
main_q2tg        |     at async Object.getEntity (/app/node_modules/telegram/client/users.js:130:25)
main_q2tg        |     at async Telegram.getChat (/app/build/client/Telegram.js:119:62)
main_q2tg        |     at async ConfigService.createLinkGroup (/app/build/services/ConfigService.js:244:26)
main_q2tg        |     at async handleMessage (/app/build/controllers/ConfigController.js:41:17)
main_q2tg        |     at async onMessage (/app/build/client/Telegram.js:66:25)
main_q2tg        |     at async _dispatchUpdate (/app/node_modules/telegram/client/updates.js:141:21)
```

</details>

**Comment by zsbai** [comment]
我也遇到了一个问题，在手动选择群组时如果群里已经有机器人了会没有任何反应，必须从群组踢掉机器人重新加一遍

**Comment by t-satoru** [comment]
![image](https://user-images.githubusercontent.com/88642005/187649992-7ee3e948-44ce-4cb5-962b-e0fd1a930894.png)
我这边更恶心，只要是先前用过的群全部报错死活设置不了，这个报错也完全看不懂，只能一键创建新群

**Comment by clansty** [comment]
这是因为你的帐号对于你选的群没有添加管理员权限

**Comment by Leao9203** [comment]
> 我也遇到了一个问题，在手动选择群组时如果群里已经有机器人了会没有任何反应，必须从群组踢掉机器人重新加一遍

个人模式也需要管理权限吗

**Comment by t-satoru** [comment]
> 这是因为你的帐号对于你选的群没有添加管理员权限

可我要添加的群是我重新部署Q2TG之前建的群啊，怎么可能没有添加管理员的权限

**Comment by zsbai** [comment]
> ![image](https://user-images.githubusercontent.com/88642005/187649992-7ee3e948-44ce-4cb5-962b-e0fd1a930894.png) 我这边更恶心，只要是先前用过的群全部报错死活设置不了，这个报错也完全看不懂，只能一键创建新群

官方文档解释：You were just elected admin, you can't add or modify other admins yet. 所以等一会儿就可以正常创建了，大概是十分钟左右。https://core.telegram.org/method/channels.editAdmin
