### ISSUE TITLE
USER_DEACTIVATED_BAN是账号有什么限制吗

### ISSUE THREAD

**Issue by 12skoko** [Clansty/Q2TG#74]
main_q2tg   | [2022-12-08T16:39:04.732] [DEBUG] Instance - 0 - 正在登录 TG Bot
main_q2tg   | [2022-12-08T16:39:04.736] [INFO] - [Running gramJS version 2.9.4]
main_q2tg   | [2022-12-08T16:39:05.282] [INFO] Instance - 0 - TG Bot 登录完成
main_q2tg   | [2022-12-08T16:39:05.282] [DEBUG] Instance - 0 - 正在登录 TG UserBot
main_q2tg   | [2022-12-08T16:39:05.283] [INFO] - [Running gramJS version 2.9.4]
main_q2tg   | [2022-12-08T16:39:05.961] [ERROR] Main - UnhandledException:  RPCError: 401: USER_DEACTIVATED_BAN (caused by users.GetUsers)
main_q2tg   |     at RPCMessageToError (/app/node_modules/telegram/errors/index.js:28:12)
main_q2tg   |     at MTProtoSender._handleRPCResult (/app/node_modules/telegram/network/MTProtoSender.js:485:58)
main_q2tg   |     at MTProtoSender._processMessage (/app/node_modules/telegram/network/MTProtoSender.js:410:15)
main_q2tg   |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
main_q2tg   |     at async MTProtoSender._recvLoop (/app/node_modules/telegram/network/MTProtoSender.js:386:17) {
main_q2tg   |   code: 401,
main_q2tg   |   errorMessage: 'USER_DEACTIVATED_BAN'
main_q2tg   | }

**Comment by 12skoko** [comment]
但是tg账号本身没有任何使用问题
