### ISSUE TITLE
TG内验证码过期问题

### ISSUE THREAD

**Issue by Nanawwa** [Clansty/Q2TG#76]
完整日志如下 已经确认过api_id与api_hash正确
但是始终无法获取最后一步验证码
```
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "db_name", schema "public" at "postgres:5432"

🚀  Your database is now in sync with your Prisma schema. Done in 177ms

✔ Generated Prisma Client (4.2.1 | library) to ./node_modules/@prisma/client in 
213ms

[2022-12-22T06:10:37.717] [DEBUG] Instance - 0 - 正在登录 TG Bot
[2022-12-22T06:10:37.720] [INFO] - [Running gramJS version 2.9.4]
[2022-12-22T06:10:37.735] [DEBUG] TelegramSession - bot:0 - Session 不存在，创建
[2022-12-22T06:10:46.478] [INFO] Instance - 0 - TG Bot 登录完成
[2022-12-22T06:10:46.479] [INFO] Instance - 0 - 当前服务器未配置，请向 Bot 发送 /setup 来设置
[2022-12-22T06:22:16.491] [INFO] SetupService - 0 - 用户 ID: ******成为了 Bot 主人
[2022-12-22T06:22:34.132] [MARK] [iPad:2015065305] - ----------
[2022-12-22T06:22:34.133] [MARK] [iPad:2015065305] - Package Version: oicq@2.3.1 (Released on 2022/6/21)
[2022-12-22T06:22:34.133] [MARK] [iPad:2015065305] - View Changelogs：https://github.com/takayama-lily/oicq/releases
[2022-12-22T06:22:34.133] [MARK] [iPad:2015065305] - ----------
[2022-12-22T06:22:34.242] [MARK] [iPad:2015065305] - ******:8080 connected
[2022-12-22T06:23:03.005] [MARK] [iPad:******] - Welcome, ****** ! 正在加载资源...
[2022-12-22T06:23:03.449] [MARK] [iPad:******] - 加载了234个好友，105个群，0个陌生人
[2022-12-22T06:23:09.142] [INFO] - [Running gramJS version 2.9.4]
[2022-12-22T06:23:09.145] [DEBUG] TelegramSession - user:0 - Session 不存在，创建
[2022-12-22T06:23:17.449] [ERROR] Main - UnhandledException:  Error: Auth key unset
    at MTProtoState.encryptMessageData (/app/node_modules/telegram/network/MTProtoState.js:142:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async MTProtoSender._sendLoop (/app/node_modules/telegram/network/MTProtoSender.js:298:20)
```

**Comment by Nanawwa** [comment]
尝试更换账号 可以收到验证码，但是填入后后台报过期验证码，多次重试也是如此。
![image](https://user-images.githubusercontent.com/57826838/209097770-84e27bae-21f4-47e9-ae3e-df7938ec69fa.png)
![image](https://user-images.githubusercontent.com/57826838/209098291-888c1136-b00c-4fe3-9be4-7f2a9cd2b4d8.png)

**Comment by Yubainc** [comment]
同样的问题，报过期验证码

![image](https://user-images.githubusercontent.com/45660358/209463782-b099d6bc-40a4-4730-a137-5cfcb793ce0a.png)
```
[2022-12-25T09:54:43.498] [ERROR] SetupService - 0 - RPCError: 400: PHONE_CODE_EXPIRED (caused by auth.SignIn)
      at RPCMessageToError (/app/node_modules/telegram/errors/index.js:28:12)
      at MTProtoSender._handleRPCResult (/app/node_modules/telegram/network/MTProtoSender.js:485:58)
      at MTProtoSender._processMessage (/app/node_modules/telegram/network/MTProtoSender.js:410:15)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async MTProtoSender._recvLoop (/app/node_modules/telegram/network/MTProtoSender.js:386:17) {
code: 400,
errorMessage: 'PHONE_CODE_EXPIRED'
```
  

会不会是弹出验证码输入窗口时会选中输入框的问题

![image](https://user-images.githubusercontent.com/45660358/209463855-f55253f6-1d34-4677-b526-7380958583d6.png)

**Comment by chiyuki0325** [comment]
![图片](https://user-images.githubusercontent.com/73830635/210055630-1beb4020-4897-4d83-b1bb-4610d33e9d88.png)
分遗产分遗产

**Comment by magisk317** [comment]
前几次报验证码不对的错，后来重试多了直接FLOOD让等几百秒到几千秒不等。。。。


![image](https://user-images.githubusercontent.com/93979778/210164959-800e5e57-ea63-4583-8236-47f83d7b0b0d.png)

**Comment by Puqns67** [comment]
同问题

```
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "Q2TG", schema "public" at "172.17.0.1:5432"

The database is already in sync with the Prisma schema.

✔ Generated Prisma Client (4.2.1 | library) to ./node_modules/@prisma/client in 
111ms

[2023-01-02T14:24:26.014] [DEBUG] Instance - 0 - 正在登录 TG Bot
[2023-01-02T14:24:26.016] [INFO] - [Running gramJS version 2.9.4]
[2023-01-02T14:24:34.029] [INFO] Instance - 0 - TG Bot 登录完成
[2023-01-02T14:24:34.029] [INFO] Instance - 0 - 当前服务器未配置，请向 Bot 发送 /setup 来设置
[2023-01-02T14:25:02.455] [INFO] SetupService - 0 - 用户 ID: XXXXXXXXX 成为了 Bot 主人
[2023-01-02T14:26:17.980] [MARK] [aPad:XXXXXXXXXX] - ----------
[2023-01-02T14:26:17.981] [MARK] [aPad:XXXXXXXXXX] - Package Version: oicq@2.3.2-clansty (Released on 2022/12/23)
[2023-01-02T14:26:17.981] [MARK] [aPad:XXXXXXXXXX] - View Changelogs：https://github.com/takayama-lily/oicq/releases
[2023-01-02T14:26:17.981] [MARK] [aPad:XXXXXXXXXX] - ----------
[2023-01-02T14:26:18.041] [MARK] [aPad:XXXXXXXXXX] - 198.18.0.20:8080 connected
[2023-01-02T14:26:18.508] [MARK] [aPad:XXXXXXXXXX] - Welcome, Σ(ﾟДﾟ) ! 正在加载资源...
[2023-01-02T14:26:18.963] [MARK] [aPad:XXXXXXXXXX] - 加载了99个好友，34个群，0个陌生人
[2023-01-02T14:26:46.356] [INFO] - [Running gramJS version 2.9.4]
[2023-01-02T14:26:46.359] [DEBUG] TelegramSession - user:0 - Session 不存在，创建
[2023-01-02T14:26:54.792] [ERROR] Main - UnhandledException:  Error: Auth key unset
    at MTProtoState.encryptMessageData (/app/node_modules/telegram/network/MTProtoState.js:142:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async MTProtoSender._sendLoop (/app/node_modules/telegram/network/MTProtoSender.js:298:20)
[2023-01-02T14:28:11.906] [ERROR] SetupService - 0 - RPCError: 400: PHONE_CODE_EXPIRED (caused by auth.SignIn)
    at RPCMessageToError (/app/node_modules/telegram/errors/index.js:28:12)
    at MTProtoSender._handleRPCResult (/app/node_modules/telegram/network/MTProtoSender.js:485:58)
    at MTProtoSender._processMessage (/app/node_modules/telegram/network/MTProtoSender.js:410:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async MTProtoSender._recvLoop (/app/node_modules/telegram/network/MTProtoSender.js:386:17) {
  code: 400,
  errorMessage: 'PHONE_CODE_EXPIRED'
}
[2023-01-02T14:28:55.778] [ERROR] SetupService - 0 - RPCError: 400: PHONE_CODE_EXPIRED (caused by auth.SignIn)
    at RPCMessageToError (/app/node_modules/telegram/errors/index.js:28:12)
    at MTProtoSender._handleRPCResult (/app/node_modules/telegram/network/MTProtoSender.js:485:58)
    at MTProtoSender._processMessage (/app/node_modules/telegram/network/MTProtoSender.js:410:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async MTProtoSender._recvLoop (/app/node_modules/telegram/network/MTProtoSender.js:386:17) {
  code: 400,
  errorMessage: 'PHONE_CODE_EXPIRED'
}
```

**Comment by Amboo-git** [comment]
我也遇到了无法登录的问题，不知道为什么输入了tg验证码一直都登不上，输入了很多次都不行，log一直说验证码过期
2023-01-02T16:21:47.112] [ERROR] SetupService - 0 - RPCError: 400: PHONE_CODE_EXPIRED (caused by auth.SignIn)
    at RPCMessageToError (/app/node_modules/telegram/errors/index.js:28:12)
    at MTProtoSender._handleRPCResult (/app/node_modules/telegram/network/MTProtoSender.js:485:58)
    at MTProtoSender._processMessage (/app/node_modules/telegram/network/MTProtoSender.js:410:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async MTProtoSender._recvLoop (/app/node_modules/telegram/network/MTProtoSender.js:386:17) {
  code: 400,
  errorMessage: 'PHONE_CODE_EXPIRED'
}

**Comment by ERR0RPR0MPT** [comment]
一样的问题，更换了两个服务器也无法解决问题。
```
[2023-01-03T20:20:05.809] [ERROR] SetupService - 0 - RPCError: 400: PHONE_CODE_EXPIRED (caused by auth.SignIn)
    at RPCMessageToError (/app/node_modules/telegram/errors/index.js:28:12)
    at MTProtoSender._handleRPCResult (/app/node_modules/telegram/network/MTProtoSender.js:485:58)
    at MTProtoSender._processMessage (/app/node_modules/telegram/network/MTProtoSender.js:410:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async MTProtoSender._recvLoop (/app/node_modules/telegram/network/MTProtoSender.js:386:17) {
  code: 400,
  errorMessage: 'PHONE_CODE_EXPIRED'
}
```

**Comment by ERR0RPR0MPT** [comment]
> 一样的问题，更换了两个服务器也无法解决问题。
> 
> ```
> [2023-01-03T20:20:05.809] [ERROR] SetupService - 0 - RPCError: 400: PHONE_CODE_EXPIRED (caused by auth.SignIn)
>     at RPCMessageToError (/app/node_modules/telegram/errors/index.js:28:12)
>     at MTProtoSender._handleRPCResult (/app/node_modules/telegram/network/MTProtoSender.js:485:58)
>     at MTProtoSender._processMessage (/app/node_modules/telegram/network/MTProtoSender.js:410:15)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async MTProtoSender._recvLoop (/app/node_modules/telegram/network/MTProtoSender.js:386:17) {
>   code: 400,
>   errorMessage: 'PHONE_CODE_EXPIRED'
> }
> ```

经过一段时间的研究，发现此问题是 Telegram 对验证码检查做了升级，貌似也会检查目前 q2tg 的使用内联键盘输入验证码的方案？总之，可以通过以下的解决方案临时解决该问题。

## 临时解决方案

下载[修改版本代码](https://github.com/Clansty/Q2TG/files/10340782/SetupService.zip)

假设 `/root/q2tg` 为运行目录，将文件解压到 `/root/q2tg/SetupService.js` 。

![Snipaste_2023-01-04_09-04-06](https://user-images.githubusercontent.com/118054130/210465910-193610ab-ad3c-4057-989a-cf0df432d03e.png)

删除所有已经构建好的容器：`docker-compose down`

修改 `docker-compose.yaml`，在 q2tg 的 volumn 中添加一行：

`- ./SetupService.js:/app/build/services/SetupService.js`

例如：

```
q2tg:
    ...

    volumes:
          - ./data:/app/data
          - ./SetupService.js:/app/build/services/SetupService.js
```

使用 `docker-compose up -d` 构建容器。

成功后，使用 `docker exec -it q2tg /bin/sh` 进入容器，之后执行 `yarn start` ，这时不要关闭 Shell 窗口。

此时会弹出 /setup 安装提示，在 Telegram 客户端上按照提示正常登录 QQ，一直到登录 TG UserBot 并需要接收验证码时，

如图所示：

![Snipaste_2023-01-04_09-09-35](https://user-images.githubusercontent.com/118054130/210466363-28956ba6-902d-4235-b4a0-fa1fa0c64cd0.png)

此时回到 Shell 窗口，输入获取到的验证码，回车。

![Snipaste_2023-01-04_09-58-06](https://user-images.githubusercontent.com/118054130/210470811-852d0e14-398d-4bd3-a49e-5c102fed4a48.png)

之后再输入两次验证密码就可以成功登录了。

@HiyoriTUK @Puqns67 @lteyox @YidaozhanYa @magisk317 @Yuaaaaaan

**Comment by magisk317** [comment]
> > 一样的问题，更换了两个服务器也无法解决问题。
> > ```
> > [2023-01-03T20:20:05.809] [ERROR] SetupService - 0 - RPCError: 400: PHONE_CODE_EXPIRED (caused by auth.SignIn)
> >     at RPCMessageToError (/app/node_modules/telegram/errors/index.js:28:12)
> >     at MTProtoSender._handleRPCResult (/app/node_modules/telegram/network/MTProtoSender.js:485:58)
> >     at MTProtoSender._processMessage (/app/node_modules/telegram/network/MTProtoSender.js:410:15)
> >     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> >     at async MTProtoSender._recvLoop (/app/node_modules/telegram/network/MTProtoSender.js:386:17) {
> >   code: 400,
> >   errorMessage: 'PHONE_CODE_EXPIRED'
> > }
> > ```
> 
> 经过一段时间的研究，发现此问题是 Telegram 对验证码检查做了升级，貌似也会检查目前 q2tg 的使用内联键盘输入验证码的方案？总之，可以通过以下的解决方案临时解决该问题。
> 
> ## 临时解决方案
> 下载[修改版本代码](https://github.com/Clansty/Q2TG/files/10340782/SetupService.zip)
> 
> 假设 `/root/q2tg` 为运行目录，将文件解压到 `/root/q2tg/SetupService.js` 。
> 
> ![Snipaste_2023-01-04_09-04-06](https://user-images.githubusercontent.com/118054130/210465910-193610ab-ad3c-4057-989a-cf0df432d03e.png)
> 
> 删除所有已经构建好的容器：`docker-compose down`
> 
> 修改 `docker-compose.yaml`，在 q2tg 的 volumn 中添加一行：
> 
> `- ./SetupService.js:/app/build/services/SetupService.js`
> 
> 例如：
> 
> ```
> q2tg:
>     ...
> 
>     volumes:
>           - ./data:/app/data
>           - ./SetupService.js:/app/build/services/SetupService.js
> ```
> 
> 使用 `docker-compose up -d` 构建容器。
> 
> 成功后，使用 `docker exec -it q2tg /bin/sh` 进入容器，之后执行 `yarn start` ，这时不要关闭 Shell 窗口。
> 
> 此时会弹出 /setup 安装提示，在 Telegram 客户端上按照提示正常登录 QQ，一直到登录 TG UserBot 并需要接收验证码时，
> 
> 如图所示：
> 
> ![Snipaste_2023-01-04_09-09-35](https://user-images.githubusercontent.com/118054130/210466363-28956ba6-902d-4235-b4a0-fa1fa0c64cd0.png)
> 
> 此时回到 Shell 窗口，输入获取到的验证码，回车。
> 
> ![Snipaste_2023-01-04_09-58-06](https://user-images.githubusercontent.com/118054130/210470811-852d0e14-398d-4bd3-a49e-5c102fed4a48.png)
> 
> 之后再输入两次验证密码就可以成功登录了。
> 
> @HiyoriTUK @Puqns67 @lteyox @YidaozhanYa @magisk317 @Yuaaaaaan

多谢，不过我到输入验证码这步的时候，终端里并没有提示让输入验证码，还是在tg里提醒，这个怎么整？
![image](https://user-images.githubusercontent.com/93979778/211772030-b7ba996f-51ba-4980-bb26-69611f045141.png)
