### ISSUE TITLE
AUTH_KEY_DUPLICATED错误

### ISSUE THREAD

**Issue by ad2248** [Clansty/Q2TG#79]
我今早突然发现Q2TG无法工作了，我看到日志在说AUTH_KEY_DUPLICATED，我就重启了docker-compose，但是还是报同样的错误。请问怎么解决呢？

附：重启后的日志
**root@vanilla:~#** docker logs main_q2tg
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "q2tg", schema "public" at "postgres:5432"

The database is already in sync with the Prisma schema.

✔ Generated Prisma Client (4.2.1 | library) to ./node_modules/@prisma/client in 
279ms

[2023-01-02T04:09:48.377] [DEBUG] Instance - 0 - 正在登录 TG Bot
[2023-01-02T04:09:48.384] [INFO] - [Running gramJS version 2.9.4]
[2023-01-02T04:09:48.991] [ERROR] Main - UnhandledException:  RPCError: 406: AUTH_KEY_DUPLICATED (caused by InvokeWithLayer)
    at RPCMessageToError (/app/node_modules/telegram/errors/index.js:28:12)
    at MTProtoSender._handleRPCResult (/app/node_modules/telegram/network/MTProtoSender.js:485:58)
    at MTProtoSender._processMessage (/app/node_modules/telegram/network/MTProtoSender.js:410:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async MTProtoSender._recvLoop (/app/node_modules/telegram/network/MTProtoSender.js:386:17) {
  code: 406,
  errorMessage: 'AUTH_KEY_DUPLICATED'
}

**Comment by Soarfree** [comment]
一样的报错

**Comment by xingyu42** [comment]
清空postgre数据库文件重新登陆试试看，我这样就可以重新登陆了
