### ISSUE TITLE
今天突然登录不上了

### ISSUE THREAD

**Issue by magisk317** [Clansty/Q2TG#95]
日志如下：
```
2023-02-15 08:53:03 main_q2tg        | [2023-02-15T00:53:03.358] [DEBUG] Instance - 0 - 正在登录 TG Bot
2023-02-15 08:53:03 main_q2tg        | [2023-02-15T00:53:03.365] [INFO] - [Running gramJS version 2.9.4]
2023-02-15 08:53:03 main_q2tg        | [2023-02-15T00:53:03.453] [ERROR] - [Error: Not connected]
2023-02-15 08:53:03 main_q2tg        | [2023-02-15T00:53:03.454] [WARN] - [Connection closed while receiving data]
2023-02-15 08:53:04 main_q2tg        | [2023-02-15T00:53:04.459] [ERROR] Main - UnhandledException:  Error: Disconnect (caused from InvokeWithLayer)
2023-02-15 08:53:04 main_q2tg        |     at /app/node_modules/telegram/extensions/MessagePacker.js:107:33
2023-02-15 08:53:04 main_q2tg        |     at Array.forEach (<anonymous>)
2023-02-15 08:53:04 main_q2tg        |     at MessagePacker.rejectAll (/app/node_modules/telegram/extensions/MessagePacker.js:105:29)
2023-02-15 08:53:04 main_q2tg        |     at MTProtoSender._disconnect (/app/node_modules/telegram/network/MTProtoSender.js:250:25)
2023-02-15 08:53:04 main_q2tg        |     at MTProtoSender.disconnect (/app/node_modules/telegram/network/MTProtoSender.js:169:20)
2023-02-15 08:53:04 main_q2tg        |     at MTProtoSender._reconnect (/app/node_modules/telegram/network/MTProtoSender.js:730:24)
2023-02-15 08:53:04 main_q2tg        |     at /app/node_modules/telegram/network/MTProtoSender.js:723:22
```

**Comment by magisk317** [comment]
大家忽略，自己傻了，本来网络环境能直连tg，后来开了代理忘记关了。。。反而连不上了
